name: slack_rtm
description: A library for Slack RTM client developers.
version: 0.0.1
homepage: https://github.com/kkazuo/dart-slack-rtm
author: Koga Kazuo <obiwanko@me.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3

dev_dependencies:
  test: ^0.12.0
